Models/ErrorViewModel.cs
namespace AddressBook.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/LOC_CountryModel.cs
using System.ComponentModel.DataAnnotations;

namespace AddressBook.Models
{
    public class LOC_CountryModel
    {
        public int ?CountryID { get; set; }
        [Required]
        public string CountryName { get; set; }
        public string CountryCode { get; set; }

        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }

    }
}

Controllers/HomeController.cs
using AddressBook.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AddressBook.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LOC_CityController.cs
    using AddressBook.DAL.LOC_CityDAL;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace AddressBook.Controllers
{
    public class LOC_CityController : Controller
    {
        LOC_CityDAL LOC_CityDAL=new LOC_CityDAL();
        public IActionResult Index()
        {
            DataTable dt=LOC_CityDAL.dbo_PR_LOC_City_SelectAll();
            return View("LOC_CityList",dt);
        }
    }
}

Controllers/LOC_CountryController.cs
using AddressBook.DAL.LOC_CountryDAL;
using AddressBook.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.SqlClient;

namespace AddressBook.Controllers
{
    public class LOC_CountryController : Controller
    {

        LOC_CountryDAL dalLOC_CountryDAL=new LOC_CountryDAL();

        private IConfiguration Configuration;
        public LOC_CountryController(IConfiguration _configuration)
        {
            Configuration = _configuration;
        }
        public IActionResult Index()
        {
            DataTable dt = dalLOC_CountryDAL.dbo_PR_LOC_Country_SelectAll();
            return View("LOC_CountryList",dt);
        }
        //public IActionResult Delete(int CountryID)1
        //{
        //    string str = this.Configuration.GetConnectionString("myConnectionString");
        //    SqlConnection conn = new SqlConnection(str);
        //    conn.Open();
        //    SqlCommand cmd = conn.CreateCommand();
        //    cmd.CommandType = System.Data.CommandType.StoredProcedure;
        //    cmd.CommandText = "PR_LOC_Country_Delete";
        //    //cmd.Parameters.AddWithValue("CountryID");
        //    cmd.ExecuteNonQuery();
        //    conn.Close();
        //    return RedirectToAction();
        //}

        public IActionResult AddEditCountryForm()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Save(LOC_CountryModel modelLOC_CountryModel)   
        {   
            string connectionstr = this.Configuration.GetConnectionString("myConnectionString");
            //PrePare a connection
            SqlConnection conn = new SqlConnection(connectionstr);
            conn.Open();

            //Prepare a Command
            SqlCommand objCmd = conn.CreateCommand();
            objCmd.CommandType = CommandType.StoredProcedure;
            if (modelLOC_CountryModel.CountryID == null)
            {
                objCmd.CommandText = "PR_LOC_Country_Insert";
                objCmd.Parameters.Add("@Created", SqlDbType.DateTime).Value = DBNull.Value;
            }
            else
            {
                objCmd.CommandText = "PR_LOC_Country_Update";
                objCmd.Parameters.Add("@CountryID", SqlDbType.Int).Value = modelLOC_CountryModel.CountryID;
            }
            objCmd.Parameters.Add("@CountryName", SqlDbType.VarChar).Value = modelLOC_CountryModel.CountryName;
            objCmd.Parameters.Add("@CountryCode", SqlDbType.VarChar).Value = modelLOC_CountryModel.CountryCode;
            objCmd.Parameters.Add("@Modified", SqlDbType.DateTime).Value = DBNull.Value;

            if (Convert.ToBoolean(objCmd.ExecuteNonQuery()))
            {
                if (modelLOC_CountryModel.CountryID == null)
                    TempData["CountryInsertMsg"] = "Record Inserted Successfully";
                else
                    return RedirectToAction("Index");
            }
            conn.Close();
            return View("AddEditCountryForm");
        }

        public IActionResult Add(int? CountryID)
        {
            if (CountryID != null)
            {
                string connectionstr = this.Configuration.GetConnectionString("myConnectionString");
                //PrePare a connection
                SqlConnection conn = new SqlConnection(connectionstr);
                conn.Open();

                //Prepare a Command
                SqlCommand objCmd = conn.CreateCommand();
                objCmd.CommandType = CommandType.StoredProcedure;
                objCmd.CommandText = "PR_LOC_Country_SelectByPK";
                objCmd.Parameters.Add("@CountryID", SqlDbType.Int).Value = CountryID;
                DataTable dt = new DataTable();
                SqlDataReader objSDR = objCmd.ExecuteReader();
                dt.Load(objSDR);

                LOC_CountryModel modelLOC_Country = new LOC_CountryModel();

                foreach (DataRow dr in dt.Rows)
                {
                    modelLOC_Country.CountryID = Convert.ToInt32(dr["CountryID"]);
                    modelLOC_Country.CountryName = dr["CountryName"].ToString();
                    modelLOC_Country.CountryCode = dr["CountryCode"].ToString();
                }

                return View("AddEditCountryForm", modelLOC_Country);
            }
            return View("AddEditCountryForm");
        }
        public IActionResult Delete(int CountryID)
        {
            string str = this.Configuration.GetConnectionString("myConnectionString");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand sqlCommand = conn.CreateCommand();
            sqlCommand.CommandType = CommandType.StoredProcedure;
            sqlCommand.CommandText = "PR_LOC_Country_Delete";
            sqlCommand.Parameters.AddWithValue("@CountryID", CountryID);
            sqlCommand.ExecuteNonQuery();
            conn.Close();
            return RedirectToAction("Index");
        }
    }
    }

Controllers/LOC_StateController.cs
using AddressBook.DAL.LOC_StateDAL;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace AddressBook.Controllers
{
    public class LOC_StateController : Controller
    {
        LOC_StateDAL _stateDAL=new LOC_StateDAL();
        public IActionResult Index()
        {
            DataTable dt=_stateDAL.dbo_PR_LOC_State_SelectAll();
            return View("LOC_StateList",dt);
        }
    }
}

Views/Home/Index.cshtml
<h3>This Is Home!!!!!</h3>

Views/LOC_City/LOC_CityList.cshtml
@using System.Data;
@model DataTable
<br />
<h3 style="justify-content:center ">City List</h3>
<br>

<table class="table">
    <thead>
        <tr>
            <th scope="col">CityID</th>
            <th scope="col">StateID</th>
            <th scope="col">CountryName</th>
            <th scope="col">StateName</th>
            <th scope="col">StateCode </th>
            <th scope="col">Created </th>
            <th scope="col">Modified </th>
            <th scope="col">CityName </th>
            <th scope="col">CityCode </th>



        </tr>
    </thead>
    <tbody>
        @foreach (DataRow dr in Model.Rows)
        {
            <tr>
                <td>@dr["CityID"]</td>
                <td>@dr["StateID"]</td>
                <td>@dr["CountryName"]</td>
                <td>@dr["StateName"]</td>
                <td>@dr["StateCode"]</td>
                <td>@Convert.ToDateTime(dr["Created"]).ToString("dd-MM-yyyy")</td>
                <td>@Convert.ToDateTime(dr["Modified"]).ToString("dd-MM-yyyy")</td>
                <td>@dr["CityName"]</td>
                <td>@dr["CityCode"]</td>


               
            </tr>
        }
    </tbody>
</table>

Views/LOC_Country/AddEditCountryForm.cshtml
@model LOC_CountryModel
@{
    ViewData["Title"] = "Country Add/Edit";
}
<h4 class="font-green-sharp">@TempData["CountryInsertMsg"]</h4>
<form method="post" asp-controller="LOC_Country" asp-action="Save">
    @Html.HiddenFor(x=>x.CountryID)
    <div class="mb-3">
        <input type="text" class="form-control"  placeholder="CountryName" asp-for="CountryName">
        <span asp-validation-for="CountryName" class="text-danger"></span>
    </div>
        <div class="mb-3">
        <input type="date" class="form-control" placeholder="Created" asp-for="Created">
        <span asp-validation-for="Created" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <input type="date" class="form-control" placeholder="Modified" asp-for="Modified">
        <span asp-validation-for="Modified" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <input type="text" class="form-control" placeholder="CountryCode" asp-for="CountryCode">
        <span asp-validation-for="CountryCode" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/LOC_Country/LOC_CountryList.cshtml
@using System.Data
@model DataTable

<br />
<table>
    <tr>
        <td ><h3 >Country List</h3></td>
        <td>
            <form>
                <input type="submit" class="btn btn-dark" value="ADD Country" asp-action="AddEditCountryForm" asp-controller="LOC_Country">
            </form>
        </td>
    </tr>
</table>
<br>

<table class="table">
    <thead>
        <tr>
            <th scope="col">CountryID</th>
            <th scope="col">CountryName</th>
            <th scope="col">CountryCode</th>
            <th scope="col">Created</th>
            <th scope="col">Modified At </th>

        </tr>
    </thead>
    <tbody>
        @foreach (DataRow dr in Model.Rows)
        {
            <tr>
                <td>@dr["CountryID"]</td>
                <td>@dr["CountryName"]</td>
                <td>@dr["CountryCode"]</td>
                <td>@Convert.ToDateTime(dr["Created"]).ToString("dd-MM-yyyy")</td>
                <td>@Convert.ToDateTime(dr["Modified"]).ToString("dd-MM-yyyy")</td>
                <td>
                    <form method="post" asp-controller="LOC_Country" asp-action="Delete">
                        <input type="hidden" name="CountryID" value="@Convert.ToInt32(dr["CountryID"])">
                        <button type="submit" class="btn btn-danger btn-xs" onclick="return fun1();" >delete</button>
                        <a class="btn btn-info btn-xs" asp-controller="LOC_Country" asp-action="Add" asp-route-countryid="@Convert.ToInt32(dr["CountryID"])">edit</a>
                    </form>
                </td>

            </tr>

        }
    </tbody>
</table>
@section Scripts
    {
    <script>
        $(document).ready(function () {
            $("#sample_1").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#sample_2 tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });

        function fun1() {
            if (confirm("Are you sure you want to delete?")) {
                return true;
            }
            else {
                return false;
            }
        }
    </script>
}

Views/LOC_State/LOC_StateList.cshtml
@using System.Data
@model DataTable
<br />
<h3>State List </h3>
<br/>
<table class="table">
    <thead>
        <tr>
            <th scope="col">StateID</th>
            <th scope="col">CountryName</th>
            <th scope="col">CountryCode</th>
            <th scope="col">StateName</th>
            <th scope="col">StateCode</th>
            <th scope="col">Created</th>
            <th scope="col">Modified</th>
        </tr>
    </thead>
    <tbody>
        @foreach (DataRow dr in Model.Rows)
        {
            <tr>
                <td>@dr["StateID"]</td>
                <td>@dr["CountryName"]</td>
                <td>@dr["CountryCode"]</td>
                <td>@dr["StateName"]</td>
                <td>@dr["StateCode"]</td>
                <td>@Convert.ToDateTime(dr["Created"]).ToString("dd-MM-yyyy")</td>
                <td>@Convert.ToDateTime(dr["Modified"]).ToString("dd-MM-yyyy")</td>
            </tr>
        }

    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AddressBook</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AddressBook.styles.css" asp-append-version="true" />
</head>
<body>
    @await RenderSectionAsync("Scripts", required: false)
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                     </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" asp-action="Index" asp-controller="LOC_Country">CountryList </a>
                    </li>
                    @*<li class="nav-item">
                        <a class="nav-link active" aria-current="page" asp-action="AddEditCountryForm" asp-controller="LOC_Country">Country Form </a>
                    </li>*@
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" asp-action="Index" asp-controller="LOC_State">StateList </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" asp-action="Index" asp-controller="LOC_City">CityList </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div>@RenderBody()</div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
 
</body>
</html>